CREATE TABLE users (
Id SERIAL PRIMARY KEY,
	Name TEXT NOT NULL,
	Email TEXT NOT NULL UNIQUE,
	CreatedAt TIMESTAMP DEFAULT NOW(),
	IsAdmin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE posts (
Id SERIAL PRIMARY KEY,
	Title TEXT NOT NULL,
	Body TEXT NOT NULL,
	CreatorId INT NOT NULL REFERENCES users(Id),
	CreatedAt TIMESTAMP DEFAULT NOW(),
	ApprovedBy INT REFERENCES users(Id)
);

CREATE TABLE tags (
	Id SERIAL PRIMARY KEY,
PostId INT NOT NULL REFERENCES posts(Id),
	CreatedAt TIMESTAMP DEFAULT NOW(),
	Tag TEXT NOT NULL
);
