// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package internal

import (
	"database/sql"
)

type FavouritePost struct {
	Postid    int64
	Userid    int64
	Createdat sql.NullTime
}

type LogEntry struct {
	ID        int64
	Tablename string
	User      int64
	Oldvalue  []byte
	Newvalue  []byte
	Createdat sql.NullTime
}

type Post struct {
	ID         int64
	Title      string
	Body       string
	Creatorid  int64
	Createdat  sql.NullTime
	Approvedby sql.NullInt64
	Approvedat sql.NullTime
}

type PostTag struct {
	Tagid     int64
	Postid    int64
	Createdat sql.NullTime
}

type PostsFt struct {
	ID       string
	Title    string
	Body     string
	PostsFts string
}

type Tag struct {
	ID        int64
	Createdat sql.NullTime
	Tag       string
}

type User struct {
	ID        int64
	Name      string
	Email     string
	Createdat sql.NullTime
	Isadmin   bool
}
