// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package internal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID         int32
	Title      string
	Body       string
	Creatorid  int32
	Createdat  pgtype.Timestamp
	Approvedby pgtype.Int4
}

type Tag struct {
	ID        int32
	Postid    int32
	Createdat pgtype.Timestamp
	Tag       string
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Createdat pgtype.Timestamp
	Isadmin   bool
}
